- README.md
- go.mod
- go.sum
- main.go
- pkg/manager/interface.go
- pkg/manager/manager.go
- pkg/manager/test_manager.go
- pkg/packages/archlinux.go
- pkg/packages/debian.go
- pkg/packages/debian_test.go
- systemd/command.go
- systemd/env.go
- systemd/node.go
- systemd/pod.go
- systemd/provider.go
- systemd/provider_test.go
- systemd/unit.go
- systemd/unit_test.go
> Complete the move to virtual-kubelet/systemk

- go.mod
- go.sum
- main.go
- pkg/manager/manager.go
- pkg/packages/debian.go
- pkg/packages/remote.go
- systemd/log.go
- systemd/pod.go
- systemd/provider.go
- systemd/provider_test.go
- systemd/unit.go
- systemd/unit_test.go
- systemd/volumes.go
this provides some unity in the logging output. At least klog is sane.
> Use klog for logging

- pkg/system/system.go
- pkg/system/system_test.go
- pkg/system/testdata/os-release-rhel77
- pkg/system/testdata/os-release-ubuntu2004
Add tests for `system.Image()` and `system.ID()`.
> system: fix OS image

- .github/workflows/go.yml
- .gitignore
- go.mod
- go.sum
- pkg/manager/manager.go
- pkg/unit/unit.go
The commit log should be self explanatory but let me know if it's not the case and I'll update the description.
> chore: misc improvements

- systemd/pod.go
> Add WorkingDir

- systemd/pod.go
- systemd/provider.go
- systemd/volumes.go
- systemd/watch.go
- systemd/watch_test.go
Ideally, informers would be exposed by the VK. However, it could have an impact on the VK performance if abused.
> provider: use informers to read/watch secrets and configmaps

- README.md
> Rewrite bits of the README

- pkg/packages/debian.go
Close the tempfile we're writing.
> Prevent text-file busy

- systemd/pod.go
Log the namespace, name and container (if available).
> logs: unify the GetXXX logs

- main.go
- systemd/provider.go
- systemd/unit_test.go
> informer factory must respect SIGINT and SIGTERM

- systemd/pod.go
Sorry for wasting your time with nit-picking.
> pod: minor code deduplication

- systemd/pod.go
First trigger stop then unload the unit in a separate loop. This mimics
how we start the units in the first place.
Also unify the logging for the 2 operations.
> Mirror unloading of units to starting

- systemd/unit.go
I don't know how others may have gotten the pod status to work with proper timestamps in conditions but this made it work for me on RHEL7 (systemd 219). Please, verify on your system and let me know.
FYI I had to fork `main.go` to also initialize logrus so the VK could complain in debug mode and point me to the problem.
Interestingly enough, while digging this I may have unearthed [a bug in VK](https://github.com/virtual-kubelet/virtual-kubelet/issues/938).
> pod: fix status update

- README.md
Discuss health check port numbers.
> Discuss port numbers

- main.go
Yes, I ran into this and it failed in spectacular ways 😭
> main: fail fast if systemd is not running

- .github/workflows/go.yml
- .github/workflows/release.yml
This kicks of a "release" whenever a release-* tag is pushed.
> Add release workflow

- internal/provider/pod.go
- internal/testdata/provider/hello.units
- internal/testdata/provider/hello.yaml
> pod: support ContainerSpec.Env

- internal/unit/manager.go
Fix comment and new newline from logline and b->B for bytes
> Small cleanup

- internal/provider/pod.go
- internal/provider/security_context.go
- internal/provider/security_context_test.go
- internal/testdata/uptimed-no-security-context.yaml
- internal/testdata/uptimed-runAsUserName.yaml
- securityContext: check and fix TODO
- put it here
> Check and combine SecurityContext/User,Group and override-root-uid

- internal/provider/volumes.go
ServiceAccountToken are moved to a new volume API - projected volumes -
add the initial ground work to support those so that pod start up
doesn't fail. The only thing I don't understand yet is the expiration
and how that's supposed to work as the backing volume is still a secret,
should probably be added to the 'watching' list as well.
Refactor the path creation into setupPaths because that we all identical
code.
Adding support for projected secrets and configmaps should now be easy.
> Support projected ServiceAccountTokens
