virtual-kubelet/systemk

pkg/packages/noop.go
systemd/provider.go

Thank you for this project, @miekg!
I'm hereby proposing a no-op package manager for scenarios where package management isn't necessary.
For instance, this would make sense in distros that aim for immutability and (may) have all the binaries that one requires available already.
I understand if this doesn't fit the project's goals and am fine if this is rejected with little to no explanation.

Introduce a no-op package manager

---

systemd/node.go

First, this addresses a problem where [_nodes are not allowed to set their role_](https://github.com/kubernetes/kubernetes/issues/84912#issuecomment-551362981). I don't know how you got this working because it doesn't work for me: get a 403 Forbidden when registering the node. Maybe it's the k3s thing that's more permissive?
Then, we set the known label `kubernetes.io/os` to `Linux`, which is what workloads usually refer to (`PodSpec.nodeSelector`) to ensure they're not placed on nodes running other OSes, ie Windows.

node: fix known labels

---

systemd/command.go
systemd/pod.go
systemd/provider_test.go
systemd/testdata/provider/prometheus.units
systemd/testdata/provider/uptimed.units
systemd/unit.go

When synthesizing a unit make the execstart empty, doing so uncovered a
couple of crashes, fix them too and make things more robust.
Fixes: #20

Make ExecStart empty

---

README.md
k3s/prometheus.yaml
main.go
pkg/manager/manager.go
pkg/system/system.go
systemd/env.go
systemd/env_test.go
systemd/node.go
systemd/provider.go
systemd/provider_test.go
systemd/testdata/provider/prometheus.units
systemd/testdata/provider/uptimed.units
systemd/unit.go

This uncovered a heap of stuff that wasn't done properly, hence the size
of the PR.
This adds 2 new flags --node-ip and --node-external-ip, which override
whatever we find ourselves. We also set this on node object. And we
export these as SYSTEMK_NODE_INTERNAL_IP and SYSTEMK_NODE_EXTERNAL_IP
(unclear if we keep this though, looks handy though). Next I want to
test this setup with Prometheus rewriting targets based on these values.
The step after that is using CoreDNS which binds the metrics to the
internal IP address by using the SYSTEMK_NODE_INTERNAL_IP env var.

export node's IP addresses as env vars

---

main.go
systemd/env.go
systemd/node.go
systemd/pod.go
systemd/provider.go
systemd/provider_test.go
systemd/unit.go
systemd/volumes.go

Since each Pod has its own root path for the volumes systemk manages, ie `/var/run/<pod uuid>`, we can simply remove said path.
I also include a couple minor changs.

feature: clean-up volumes on Pod deletion

---

README.md
go.mod
main.go
systemd/env_test.go
systemd/noop_logger.go
systemd/provider.go
systemd/provider_test.go
systemd/volumes.go
systemd/volumes_test.go

This adds extra security to force mountspoints to be below a specified
path list (defaults to "/var"), as to prevent system modifications.
This is also showed HostPaths don't work, but appeared to work because
everything was done as root.
Also remove stray println in tests and cleanup the test output (disable
logging)

Add --dir -d flag to force mounts points be below a path

---

systemd/pod.go

Found this when a Pod that isn't supported by `systemk` got scheduled onto it..
```
I0110 23:52:07.354344    2619 pod.go:65] CreatedPod called
I0110 23:52:07.354576    2619 volumes.go:41] Looking at volume "kube-proxy"#0
I0110 23:52:07.354876    2619 volumes.go:125] Created "/var/run/6a30ca6e-2f9b-49a4-940e-5cb26e020eae/configmaps/#0" for configmap: kube-proxy
I0110 23:52:07.355169    2619 volumes.go:177] Chowning "/var/run/6a30ca6e-2f9b-49a4-940e-5cb26e020eae/configmaps/#0/systemk.808583862.tmp" to .
I0110 23:52:07.355409    2619 volumes.go:186] Writing data "apiVersion" to path "/var/run/6a30ca6e-2f9b-49a4-940e-5cb26e020eae/configmaps/#0/systemk.808583862.tmp"
I0110 23:52:07.355696    2619 volumes.go:191] Renaming /var/run/6a30ca6e-2f9b-49a4-940e-5cb26e020eae/configmaps/#0/systemk.808583 …
```

pod: don't process volumes if package fails to install

---

.gitignore
README.md
main.go
pkg/system/system.go
systemd/env.go
systemd/node.go
systemd/provider.go
systemd/provider_test.go
systemd/unit.go

Fixes #6
Also, as agreed over Slack, I'm enforcing Node Leases API to be used.
Oh, I've added some instructions for people who want to test against different local Kubernetes solutions, most notably `kind` and `minikube`. This will be truly useful when implementing e2e tests, like we did for VK, which also uses `minikube`.

cli: respect flag --nodename

---

systemd/provider.go

The if the euid is 0, otherwise skip the installation step (will fail
anyway, but that's a fatal error)
See: #30

Skip debian package pre-install if not root

---

systemd/provider.go
systemd/testdata/provider/hello.units
systemd/testdata/provider/hello.yaml
systemd/watch.go
systemd/watch_test.go

Pod deletion carries a Pod with no Volumes, hence unwatch was not really working. Unfortunately, the unit tests were not capturing this, which I tentatively address in this PR - knowing the true one solution is to implement e2e tests.

pod: fix unwatch

---

main.go
systemd/provider.go

This is handy to specify a systemk.service file which uses these
defaults *and* allows them to be overriden
~~~
Environment="NODE_IP=0.0.0.0"
Environment="NODE_EXTERNAL_IP=0.0.0.0"
EnvironmentFile=/etc/default/systemk
~~~
Default is autodetect unless /etc/default/systemk overrides it, this
means the unit file is static and doesn't need to be changed.

main: allow --node-ip and --node-external-ip to have 0.0.0.0 value

---

main.go

Correct set the hostname to the node's name. This code makes all systemk
instances report 'virtual-kubelet' while we want it to be the hostname.

Looking up the flag doesn't work

---

README.md
main.go
systemd/pod.go
systemd/provider.go
systemd/unit_test.go

Connect to a user's systemd instead of the system wide one when the -u
flag is given. This also means that (probably?) the User and Group
settings in the unit file should be removed, because we can't become
another user in a user process.

user systemd support

---

internal/system/system.go

`systemd --version` doesn't work on RHEL7 systems.
This change works on Ubuntu 20.04 so I take this change as safe.
```
System Info:
Machine ID:
System UUID:
Boot ID:
Kernel Version:             5.4.0-60-generic
OS Image:                   Ubuntu 20.04.1 LTS
Operating System:           Linux
Architecture:               amd64
Container Runtime Version:  systemd 245 (245.4-4ubuntu3.3)
Kubelet Version:            v1.18.15
Kube-Proxy Version:
```

node: container runtime feeds from systemctl

---

.github/workflows/go.yml
cmd/http.go
internal/provider/pod.go
internal/testdata/provider/hello.units
internal/testdata/provider/hello.yaml

... instead of doing it through journalctl CLI.
This is the first step to address #5. What's missing and will eventually be addressed in separate PRs?
- follow mode support
- retrieving logs pertaining to the current Pod, in case a homonym Pod once existed for which journald still has entries for.
Some examples of a Pod named `hello`, that simply prints `date`, every 5 seconds:
`kubectl logs --since`:
```
$ k logs --since 20s hello
Thu Jan 21 23:20:52 WET 2021
Thu Jan 21 23:20:57 WET 2021
Thu Jan 21 23:21:02 WET 2021
Thu Jan 21 23:21:07 WET 2021
$k logs --since 1m hello
Thu Jan 21 23:20:17 WET 2021
Thu Jan 21 23:20:22 WET 2021
Thu Jan 21 23:20:27 WET 2021
Thu Jan 21 23:20:32 WET 2021
Thu Jan 21 23:20:37 WET 2021
Thu Jan 21 23:20:42 WET 2021
Thu Jan 21 23:20:47 WET 2021
Thu Jan 21 23:20:52 …
```

node: retrieve logs from journal socket

---

cmd/http.go
internal/provider/log.go
internal/provider/pod.go
internal/provider/provider.go

This is the final step to fix #5
https://user-images.githubusercontent.com/1752631/105516932-57251b00-5cce-11eb-9b68-2efffb1e5623.mov

node: support following logs

---

internal/provider/node.go
internal/provider/provider.go

```
System Info:
Machine ID:                 065b96dc0f1f4f668a4d2f5f8418ae42
System UUID:
Boot ID:
Kernel Version:             5.4.0-62-generic
OS Image:                   Ubuntu 20.04.1 LTS
Operating System:           Linux
Architecture:               amd64
Container Runtime Version:  systemd 245 (245.4-4ubuntu3.4)
Kubelet Version:            v1.18.15
```
Also, fixed a typo with a more meaningful message when an unsupported OS package management is found.

node: machine ID is set in Node info

---

internal/provider/pod.go
internal/provider/pod_test.go
internal/provider/unit.go
internal/testdata/provider/hello.units
internal/testdata/provider/prometheus.units
internal/testdata/provider/prometheus.yaml
internal/testdata/provider/uptimed.units

This clears up the Image == Name confusion. Add some documentation to
the Container, Namespace, Pod and Image functions that makes clearer how they
are used.
The image name is now stored in the X-Kubernetes section of the unit
Closes: #42

Use Container instead of Image

---

internal/provider/pod.go
internal/provider/provider.go
internal/provider/provider_test.go
internal/provider/volumes.go

This moves the configmap/secrets/emptydir stuff under /var/run/user/$UID
when run with the -u flag.
A user mode ran systemk still needs CAP_CHOWN to the chown the dir to
the user of the pod - but we may be able to ignore that error.
Previously systemk would just not run any pods in usermode because it
can create any of the volumes for the pod.

user mode: use /var/run/user/$UID for other dirs as well

---

internal/provider/unit.go

The name of the container, must be the `Container` not `Name` as this
doubles the namespace in it leading to bugs where you can't find the
unit file you started.

Fix container name

---

README.md
cmd/flag.go
internal/provider/opts.go
internal/provider/pod.go
internal/provider/provider.go
internal/unit/manager.go

This removes the -u flag and assorted code, i.e. we will always use the
system's systemd (and run as root).
Left a TODO that I will shortly address to map to a non-root user (if
that flag is set) if the unit file says run as root and no security
context is provided in the prodspec.

Remove user mode

---

cmd/flag.go

Only leave the klog.v flag. For some reason this logging lib has the
majority of the number of flags.

Remove all but one klog flags

---

cmd/flag.go
internal/provider/opts.go
internal/provider/pod.go
internal/provider/security_context.go
internal/provider/security_context_test.go
internal/provider/volumes.go
internal/testdata/uptimed-config.yaml
main.go

This maps the root user to another ID, meaning no pods will be run with
root perms. This is an alternative approach to the failed, run systemk
as a user.
Test the security context parsing and make it return an error as well.

add map-root flag

---

internal/provider/pod.go

Remove the tmp variable and name it tmpfs to slightly better convey
how it will be used. Pull the join out of the loop also.

Remove tmp variable

---

cmd/flag.go
cmd/root.go
main.go

The nodename is not working, the instalFlags would overwrite the
Opts with the default value in the flag string. So it would overwrite
it (in the case of nodename) with the empty value. This shows when
you don't have the HOSTNAME env var set (the case in my zsh setup)
Move this into the correct order, first set the flags, then set the
default options if the flag isn't set.

Fix nodename setting

---

cmd/flag.go
internal/provider/node.go
internal/provider/opts.go
internal/system/system.go
internal/system/system_test.go

This takes the 1 address of the *interface* and uses this for internal
or external node IP. This saves a whole bunch of external parsing (ip
addr show | grep ...) to get this IP.
E.g. I've got another (more stable) address configured on lo:1, so just
specifying the iface would make the unit file more portible and less
fragile because no iface parsing scripts needs to be executed.

Add --internal|--external-iface

---

internal/ospkg/debian.go
internal/ospkg/remote.go

This string was first removed and then added. Stop doing that.
Also matches the 'fetch' comment better.

ospkg: don't remove and then add 'https://'

---

internal/provider/pod.go
internal/provider/volumes.go

I don't think there is a need to fiddle with this directory, also when
multiple pods run with different users we chown to diff. users, which
makes no sense.

Let systemd create the mount path for us

---

internal/provider/pod.go

This was matching the prefix, which meant that uptime2 and uptime would
both be matched when we look for 'uptime'. Add the separator to the
matching so this doesn't happen.

Match the complete prefix for the units

---

README.md
cmd/flag.go
internal/provider/opts.go
internal/provider/provider_test.go
internal/provider/volumes.go
internal/provider/volumes_test.go

Remove this feature. It was used to restrict where we (bind)mount, but
systemk controls that location, so no need to restrict.

Remove retricting mount paths
